package View;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author N7559
 */
public class LoginPage extends javax.swing.JPanel {

    /**
     * Creates new form menuTeacher
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoTU1 = new javax.swing.JLabel();
        loginNametxt = new javax.swing.JLabel();
        nameSurname = new javax.swing.JLabel();
        logoutBtt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        logoTU2 = new javax.swing.JLabel();
        loginNametxt1 = new javax.swing.JLabel();
        nameSurname1 = new javax.swing.JLabel();
        exportTxt = new javax.swing.JButton();
        createBtt = new javax.swing.JButton();
        exportTxt1 = new javax.swing.JButton();
        deleteBtt = new javax.swing.JButton();
        exportTxt3 = new javax.swing.JButton();
        exportTxt4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 233, 114));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        logoTU1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo-TU.png"))); // NOI18N

        loginNametxt.setFont(new java.awt.Font("Century Gothic", 0, 33)); // NOI18N
        loginNametxt.setText("Login name : ");

        nameSurname.setFont(new java.awt.Font("Century Gothic", 0, 33)); // NOI18N
        nameSurname.setText("NAME + SURNAME");

        logoutBtt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logoutBtt.setForeground(new java.awt.Color(51, 51, 51));
        logoutBtt.setText("logout");
        logoutBtt.setBorder(null);
        logoutBtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBttMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoTU1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(loginNametxt)
                        .addGap(18, 18, 18)
                        .addComponent(nameSurname)
                        .addContainerGap(513, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutBtt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutBtt)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(loginNametxt)
                                .addComponent(nameSurname))
                            .addGap(66, 66, 66))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(logoTU1)
                            .addContainerGap()))))
        );

        jPanel2.setBackground(new java.awt.Color(255, 233, 114));
      //  jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        logoTU2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo-TU.png"))); // NOI18N

        loginNametxt1.setFont(new java.awt.Font("Century Gothic", 0, 33)); // NOI18N
        loginNametxt1.setText("Login name : ");

        nameSurname1.setFont(new java.awt.Font("Century Gothic", 0, 33)); // NOI18N
        nameSurname1.setText("NAME + SURNAME");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoTU2)
                .addGap(34, 34, 34)
                .addComponent(loginNametxt1)
                .addGap(33, 33, 33)
                .addComponent(nameSurname1)
                .addContainerGap(498, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(logoTU2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginNametxt1)
                            .addComponent(nameSurname1))
                        .addGap(66, 66, 66))))
        );

       // jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 220));

        exportTxt.setBackground(new java.awt.Color(255, 153, 0));
        exportTxt.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        exportTxt.setForeground(new java.awt.Color(255, 153, 0));
        exportTxt.setText("Coming soon");

        createBtt.setBackground(new java.awt.Color(255, 153, 0));
        createBtt.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        createBtt.setForeground(new java.awt.Color(255, 153, 0));
        createBtt.setText("Create subject");

        exportTxt1.setBackground(new java.awt.Color(255, 153, 0));
        exportTxt1.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        exportTxt1.setForeground(new java.awt.Color(255, 153, 0));
        exportTxt1.setText("Export file");

        deleteBtt.setBackground(new java.awt.Color(255, 153, 0));
        deleteBtt.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        deleteBtt.setForeground(new java.awt.Color(255, 153, 0));
        deleteBtt.setText("Delete subject");

        exportTxt3.setBackground(new java.awt.Color(255, 153, 0));
        exportTxt3.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        exportTxt3.setForeground(new java.awt.Color(255, 153, 0));
        exportTxt3.setText("List student");

        exportTxt4.setBackground(new java.awt.Color(255, 153, 0));
        exportTxt4.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        exportTxt4.setForeground(new java.awt.Color(255, 153, 0));
        exportTxt4.setText("Change criterion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createBtt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteBtt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportTxt4))
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exportTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportTxt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBtt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createBtt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>                        

    private void logoutBttMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
    }                                      


    // Variables declaration - do not modify                     
    private javax.swing.JButton createBtt;
    private javax.swing.JButton deleteBtt;
    private javax.swing.JButton exportTxt;
    private javax.swing.JButton exportTxt1;
    private javax.swing.JButton exportTxt3;
    private javax.swing.JButton exportTxt4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel loginNametxt;
    private javax.swing.JLabel loginNametxt1;
    private javax.swing.JLabel logoTU1;
    private javax.swing.JLabel logoTU2;
    private javax.swing.JButton logoutBtt;
    private javax.swing.JLabel nameSurname;
    private javax.swing.JLabel nameSurname1;
    // End of variables declaration                   
}
